In [ ]:
pip install numpy

In [ ]:
import numpy as np

In [ ]:
arr=np.array([1,2,3])

In [35]:
arr_2d=np.array([[1,2,3],[4,5,6]])

In [36]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [37]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [38]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [39]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [12]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [13]:
np.random.rand(3,2)

array([[0.28394941, 0.3988299 ],
       [0.20778055, 0.95761683],
       [0.8424581 , 0.6943864 ]])

In [14]:
np.random.randn(3,2)

array([[ 1.00223724,  0.40400575],
       [-0.19796992, -0.65696579],
       [ 0.09649735, -0.45906776]])

In [15]:
arr=np.array([[1,2,3],[4,5,6]])

In [17]:
print(arr.shape)

(2, 3)


In [19]:
print(arr.ndim)

2


In [20]:
print(arr.size)

6


In [21]:
print(arr.dtype)

int64


In [ ]:
#Basic math

In [24]:
a=np.array([1,2,3])

In [25]:
b=np.array([1,2,3])

In [26]:
a+b

array([2, 4, 6])

In [ ]:
a*b

In [ ]:
np.sin(a)

In [ ]:
#Matrix Multiplication

In [27]:
A=np.array([1,2,3,4])

In [ ]:
arr.min()

In [28]:
arr.std()

np.float64(1.707825127659933)

In [29]:
#1D Array

In [31]:
arr=np.array([1,2,3,4,5])

In [32]:
#2D Arrays

In [40]:
arr=np.array([[1,2,3],[4,5,6]])

In [41]:
mask=arr>3

In [42]:
arr[mask]

array([4, 5, 6])

In [55]:
#Reshape

In [58]:
arr=np.arange(6)

In [69]:
#Concentention

In [70]:
a=np.array([1,2])

In [71]:
b=np.array([3,4])

In [72]:
np.concatenate((a,b))

array([1, 2, 3, 4])

In [73]:
#Stacking

In [74]:
np.vstack((a,b))

array([[1, 2],
       [3, 4]])

In [75]:
np.hstack((a,b))

array([1, 2, 3, 4])

In [76]:
a+5#[6,7,8]

array([6, 7])

In [77]:
#save to file

In [78]:
np.save('array.npy',arr)

In [79]:
#Load from a np.load('array.npy')